version: '2'
services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    volumes:
      - /mnt/storage/containers/plex:/config
      - /mnt/storage/media:/data
    network_mode: host
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
  tautulli:
    image: tautulli/tautulli
    container_name: tautulli
    volumes:
      - /mnt/storage/containers/tautulli:/config
      - /mnt/storage/containers/plex/Library/Application\ Support/Plex\ Media\ Server/Logs:/plex_logs:ro
    ports:
      - 8181:8181
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
  sabnzbd:
    image: linuxserver/sabnzbd:latest
    container_name: sabnzbd
    volumes:
      - /mnt/storage/containers/sabnzbd:/config
      - /mnt/storage/media/downloads/complete:/downloads
      - /mnt/storage/media/downloads/incomplete:/incomplete-downloads
    ports:
      - 8080:8080
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    volumes:
      - /mnt/storage/containers/sonarr:/config
      - /mnt/storage/media/tvseries:/tv
      - /mnt/storage/media/downloads/complete/tvseries:/downloads
    ports:
      - 8989:8989
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    volumes:
      - /mnt/storage/containers/radarr:/config
      - /mnt/storage/media/movies:/movies
      - /mnt/storage/media/downloads/complete/movies:/downloads
    ports:
      - 7878:7878
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    restart: always
  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    volumes:
      - /mnt/storage/media/music:/music
      - /mnt/storage/containers/lidarr:/config
      - /mnt/storage/media/downloads/complete/music:/downloads
    ports:
      - 8686:8686
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
  watchtower:
    image: v2tec/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    command: --schedule "0 0 4 * * *" --cleanup
  organizr:
    container_name: organizr
    restart: always
    image: lsiocommunity/organizr
    volumes:
      - /mnt/storage/containers/organizr:/config
    ports:
      - "80:80"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ="America/New_York"
